### PR TITLE
Added Support For Chars Colors

### PR DESCRIPTION
**Pull request by PeterHindes**
Is this good? I saw some functions that also clear the screen and what not, should those be implemented for chars too?

### CODE REVIEW

**Comment by PeterHindes** [comment]
Now we can bold and other styles on a char

**Comment by PeterHindes** [comment]
Done

**Comment by TimonPost** [comment]
Thanks again!

**Comment by PeterHindes** [comment]
I don't know if you want it, but I added an example to my forked repository just now. Merge it if you want.

**Pull request merged**
