### PR TITLE
Update to signal-hook-mio 0.8

### PR DESCRIPTION
**Pull request by pickfire**

### CODE REVIEW

**Review by TimonPost — APPROVED** [review]
Awesome!

**Comment by pickfire** [comment]
@TimonPost Is there still anything left for this to be merged or are you waiting for a release?

**Comment by TimonPost** [comment]
Nope :) I'll do a release soon!

**Comment by pickfire** [comment]
I think you forgot to release to crates.io https://crates.io/crates/crossterm, I noticed the same thing with https://github.com/vorner/signal-hook/pull/131#issuecomment-1079916912

**Comment by TimonPost** [comment]
It's a phenomenon called 'bussy' and 'not that high of a priority'. Not that crossterm is un important, its just that other things consume energy in the daily life of programming, and this is more or less a community driven project at the moment. Cant speak for others, but think that's it 😉

**Pull request merged**
