### PR TITLE
Add SetCursorStyle command

### PR DESCRIPTION
**Pull request by TimonPost**
Adds a command to set the cursor style.

Fixes: #646 , maybe #740

### CODE REVIEW

**Comment by Cl00e9ment** [comment]
I was just about to create a pull request but you were faster!

I don't know if it's useful, but here is my version:
https://github.com/Cl00e9ment/crossterm/tree/feat-set-cursor-style

**Comment by TimonPost** [comment]
Oh whoops, what a coincidence, im sorry, let me look at that.

**Comment by TimonPost** [comment]
I decided to keep enable / disable blinking. Those are very specific and a user might not know which cursor shape it uses. So allowing to have this separately may allow a user to control blinking for the current active cursor

**Comment by Cl00e9ment** [comment]
> I decided to keep enable / disable blinking. Those are very specific and a user might not know which cursor shape it uses.

Yes but these commands are broken on certain terminals so a note should be added.

> If you want to follow up and improve there is time to do that!

I'll do that!

**Pull request merged**
