### PR TITLE
Changed STDIN to /dev/tty

### PR DESCRIPTION
**Pull request by TimonPost**

### CODE REVIEW

**Comment by japert** [comment]
I tried this branch on macOS 10.15.4.
Getting:
```
$ cargo run --features="event-stream" --example event-stream-tokio
thread 'main' panicked at 'Event source can not be initialized: IoError(Os { code: 22, kind: InvalidInput, message: "Invalid argument" })', src/event/read.rs:30:17
               note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Which is the sam IoError I got on macOS on cross term 0.17

**Comment by japert** [comment]
After the merge, I am still getting the same IOError.

**Comment by extrawurst** [comment]
@japert yup I can confirm it’s still throwing the error on macOs

**Comment by TimonPost** [comment]
Its unfortunate I cant test on mac os. It is right that in 0.17 there was a bug with the TTY. I reverted that bug with https://github.com/crossterm-rs/crossterm/pull/405/files, however this Pr introduces the same problem again. For some reason, on mac os, we cant use the TTY for input reading. It throws an error if we are opening the file.

**Comment by acidghost** [comment]
This because of tokio-rs/mio#1377.

**Comment by TimonPost** [comment]
Amazing! That could be the issue. Thanks for linking.

**Comment by cosmikwolf** [comment]
for anyone trying to get stdin working with crossterm, but having a hard time, I made an example repo on how to do it:
https://github.com/cosmikwolf/piped_cli_interactive

**Pull request closed without merging**
